version: "3.5"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile

  db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-volume: